version: "3.6"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: kiro
      POSTGRES_USER: kiro_sql
      POSTGRES_PASSWORD: test
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./backups:/backups
  back:
    build:
      context: back
      dockerfile: Dockerfile
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/src
      - ./backups:/backups
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
  front:
    build: 
      context: front
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src:rw
      - ./front/public:/app/public:rw
      - ./front/package.json:/app/package.json:rw