# Generated by Django 4.2.1 on 2023-05-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('Autre', 'Other'), ('Centrale Supélec', 'Cs'), ('École polytechnique', 'X'), ('École des Ponts', 'Enpc'), ('ENSAE', 'Ensae'), ('HEC', 'Hec'), ('ENS', 'Ens')], default='Autre', max_length=255),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.team')),
            ],
        ),
    ]
