# Generated by Django 4.1.2 on 2023-07-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_school_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.team'),
        ),
    ]
