# Generated by Django 4.1.2 on 2023-08-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_school_year_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teachers',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
